Repository Konkuk-KUIT/KUpage-FE, pull requests merged in 2025-05, with the labels that each got.

#9 Fix: Reapply API setting (PR #6) on top of PR #7 (Routing)
  .eslintrc.cjs
  .gitignore
  .prettierrc
  README.md
  eslint.config.js
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/Router.tsx
  src/components/home/StaffCardBack.tsx
  src/components/home/StaffCardFront.tsx
  src/components/home/StaffContent.tsx
  src/constants/BaseName.ts
  src/main.tsx
  src/pages/Global/ErrorPage.tsx
  src/pages/Global/Footer.tsx
  src/pages/Global/Header.tsx
  src/pages/Global/Layout.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/pages/Signup/Signup.tsx
  tsconfig.app.json
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
  vite.config.ts
Labels: 🛠️ fix, 🐹 수아

#11 [Feat] Projects 목록 페이지 구현
  src/Router.tsx
  src/components/Project/ProjectCohortTab.tsx
  src/components/Project/ProjectCohortTabs.tsx
  src/components/Project/ProjectDetailCard.tsx
  src/constants/CohortConstants.ts
  src/pages/Home/Home.tsx
  src/pages/Project/Projects.tsx
  tailwind.config.ts
Labels: 💄 UI, 💫 feat, 🐹 수아

#12 [UI] Recruit 페이지 구현
  package-lock.json
  src/Router.tsx
  src/assets/imgs/ArrowDown.svg
  src/assets/imgs/CarouselBtnLeft.svg
  src/assets/imgs/CarouselBtnRight.svg
  src/assets/imgs/Github.svg
  src/components/commons/TextChip.tsx
  src/components/home/RoleChip.tsx
  src/components/home/RoleChipRow.tsx
  src/components/home/StaffCardBack.tsx
  src/components/home/StaffContent.tsx
  src/components/recruit/CurriculumCarousel.tsx
  src/components/recruit/FAQAccordion.tsx
  src/components/recruit/RecruitDescriptionBlock.tsx
  src/components/recruit/RecruitFieldSection.tsx
  src/components/recruit/RecruitHeader.tsx
  src/constants/RecruitCostants.tsx
  src/constants/curriculumConstants.ts
  src/constants/faqConstants.ts
  src/pages/Recruit/Recruit.tsx
  tailwind.config.ts
Labels: 💄 UI, 😽 나은

#15 [Feat] improve Home page
  src/components/home/Counter.tsx
  src/components/home/InProgressBox.tsx
  src/components/home/ProjectCard.tsx
  src/components/home/StaffCardRow.tsx
  src/pages/Home/Home.tsx
Labels: 🍀 refactor, 💄 UI, :turtle: 지환
